name: Checkmarx One Scan

on:
  push:
    branches: [sonarCxScanAction]

jobs:
  CxOneScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install Checkmarx AST CLI
        run: |
          # Create directory for CLI
          mkdir -p cx-cli

          # Download the CLI archive
          curl -L https://github.com/Checkmarx/ast-cli/releases/download/2.3.18/ast-cli_linux_x64.tar.gz -o cx-cli/ast-cli.tar.gz

          # Extract the archive
          tar -xzf cx-cli/ast-cli.tar.gz -C cx-cli

          # Make the CLI executable
          chmod +x cx-cli/cx

          # Add to PATH
          echo "$(pwd)/cx-cli" >> $GITHUB_PATH

      - name: Configure Checkmarx One CLI
        env:
          CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
          CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
          CX_TENANT: ${{ secrets.CX_TENANT }}
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_BASE_AUTH_URI: ${{ secrets.CX_BASE_AUTH_URI }}
        run: |
          cx configure set \
            --base-uri "$CX_BASE_URI" \
            --base-auth-uri "$CX_BASE_AUTH_URI" \
            --tenant "$CX_TENANT" \
            --client-id "$CX_CLIENT_ID" \
            --client-secret "$CX_CLIENT_SECRET" \
            --profile "default"

      - name: Check version and authenticate
        run: |
          cx version
          cx auth validate
